# Generated by Django 4.0.1 on 2022-01-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give_it_away_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('type', models.IntegerField(choices=[(1, 'Fundacja'), (2, 'Organizacja pozarządowa'), (3, 'Zbiórka lokalna')])),
                ('categories', models.ManyToManyField(to='give_it_away_app.Category')),
            ],
        ),
    ]
